Release

diff --git a/arch-restore b/arch-restore
--- a/arch-restore
+++ b/arch-restore
@@ -1,23 +1,64 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
+
+VERSION="1.0.0"
+PROGNAME="$(basename "$0")"
+
+usage() {
+	cat<<EOF
+$PROGNAME version $VERSION
+
+Usage: $PROGNAME [options] [archive]
+
+Options:
+    -h, --help		-Show this help message
+    -V, --version 	-Show script version
+
+Example $PROGNAME
+	$PROGNAME 2025-08-12_12-49-54.tar.gz
+
+EOF
+}
+ARCHIVE=""
+
+if [ $# -gt 0 ]; then
+	case "$1" in
+		-h|--help)
+			usage
+			exit 0	
+			;;
+		-V|--version)
+			echo ""$PROGNAME" version $VERSION"
+			exit 0
+			;;
+		*)
+			ARCHIVE="$1"
+			shift
+			;;
+		-*)
+			echo "Unknown option: $1"
+			exit 1
+			;;
+	esac
+fi
 
 BACKUP_ROOT="$HOME/backup"
 
-if [ -n "$1" ]; then
-	ARCHIVE="$1"
-else
-	ARCHIVE=$(ls -1t "$BACKUP_ROOT"/*.tar.gz 2>/dev/null | head -n 1)
+if [ -z "$ARCHIVE" ]; then
+	echo "[*] No archive specified, searching fot the latest backup in $BACKUP_ROOT ..."
+	ARCHIVE=$(ls -t "$BACKUP_ROOT"/*.tar.gz 2>/dev/null | head -n 1 || true)
 	if [ -z "$ARCHIVE" ]; then
-		echo "[!] Backups not found in $BACKUP_ROOT"
+		echo "[!] No backup archive found in $BACKUP_ROOT"
 		exit 1
 	fi
 	echo "[*] Using latest backup: $ARCHIVE"
-fi
-
-if [ ! -f "$ARCHIVE" ]; then
-	echo "[!] Archive $ARCHIVE not found"
-	exit 1
+else
+	if [ ! -f "$ARCHIVE" ]; then
+		echo "[!] Specified archive not found: $ARCHIVE"
+		exit 1
+	fi
+	echo "[*] Using specified backup archive: $ARCHIVE"
 fi
 
 if [ -f "$ARCHIVE.sha256" ]; then
